
name: flutter_exam_five
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  flutter_local_notifications: ^12.0.2
  intl: ^0.17.0

  # Architecture
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  json_serializable: ^6.4.1
  formz: ^0.4.1
  firebase_messaging: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:

  uses-material-design: true